name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Provision EC2 and Deploy HTML
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform 

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Устанавливаем Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     
    
    - name: Terraform Apply
      env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -var="public_key=${{ secrets.SSH_PUBLIC_KEY }}"



    # 5. Получаем IP-адрес EC2 инстанса из output Terraform
    - name: Get EC2 public IP
      id: ec2_ip
      run: echo "EC2_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV

    # 6. Копируем index.html на EC2 через SCP
    - name: Copy index.html to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ env.EC2_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "../index.html"
        target: "/var/www/html"
