name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Copy files to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files using SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "index.html"
        target: "/var/www/html"
